name: hp-printer-app
base: core22
version: '1.2.1'
summary: HP Printer Application
description: |
  HP Printer Application is sample printer application for Hewlett Packard PCL
  (and compatible) printers.  It is based on PAPPL (Printer Application
  Framework), a simple C-based framework/library for developing CUPS Printer
  Applications, which are the recommended replacement for printer drivers.

grade: stable
confinement: strict
icon: hp-printer-app.png

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
    hp-printer-app:
        command: bin/hp-printer-app
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

    hp-printer-app-server:
        command: bin/hp-printer-app-server
        daemon: simple
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

hooks:
    configure:
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

parts:
    libcups:
        plugin: autotools
        autotools-configure-parameters: [--disable-shared,--prefix=/usr,--sysconfdir=/etc,--with-components=libcupslite,--with-dnssd=avahi]
        source: https://github.com/OpenPrinting/cups/releases/download/v2.4.2/cups-2.4.2-source.tar.gz
        build-packages: [libavahi-client-dev, libgnutls28-dev, libjpeg8-dev, libpam-dev, libpng-dev, libusb-1.0-0-dev, zlib1g-dev]
        stage-packages: [libavahi-client3, libjpeg8, libpng16-16, libusb-1.0-0]

    pappl:
        plugin: autotools
        autotools-configure-parameters: [--disable-shared,--enable-libjpeg,--enable-libpng,--enable-libusb,--prefix=/,--with-dnssd=avahi]
        source: https://github.com/michaelrsweet/pappl/releases/download/v1.3.1/pappl-1.3.1.tar.gz
        build-packages: [libavahi-client-dev, libgnutls28-dev, libjpeg8-dev, libpam-dev, libpng-dev, libusb-1.0-0-dev, zlib1g-dev]
        stage-packages: [libavahi-client3, libjpeg8, libpng16-16, libusb-1.0-0]
        after: [libcups]

    hooks:
        plugin: dump
        source: snap/local/hooks
        organize:
          configure: snap/hooks/

    scripts:
        plugin: dump
        source: snap/local/scripts
        organize:
          hp-printer-app-server: bin/

    hp-printer-app:
        plugin: make
        source: .
        make-parameters: [prefix=]
        after: [libcups, pappl, hooks, scripts]
