name: hp-printer-app
base: core22
version: '1.2.1'
summary: HP Printer Application
description: |
  HP Printer Application is sample printer application for Hewlett Packard PCL
  (and compatible) printers.  It is based on PAPPL (Printer Application
  Framework), a simple C-based framework/library for developing CUPS Printer
  Applications, which are the recommended replacement for printer drivers.

grade: stable
confinement: strict
icon: hp-printer-app.png

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
    hp-printer-app:
        command: bin/hp-printer-app
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

    hp-printer-app-server:
        command: bin/hp-printer-app-server
        daemon: simple
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

hooks:
    configure:
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

parts:
    pappl:
        plugin: autotools
        autotools-configure-parameters: [--disable-shared,--enable-libjpeg,--enable-libpng,--enable-libusb,--with-dnssd=avahi]
        source: https://github.com/michaelrsweet/pappl/releases/download/v1.3.1/pappl-1.3.1.tar.gz
        build-packages: [libavahi-client-dev, libcups2-dev, libcupsimage2-dev, libgnutls28-dev, libjpeg8-dev, libpam-dev, libpng-dev, libusb-1.0-0-dev, zlib1g-dev]
        stage-packages: [libavahi-client3, libcups2, libcupsimage2, libjpeg8, libpng16-16, libusb-1.0-0]

    hp-printer-app:
        plugin: make
        source: .
        make-parameters: prefix=
        after: [pappl]

    hooks:
        plugin: dump
        source: snap/hooks
        organize:
          hp-printer-app-server: snap/hooks/
        after: [hp-printer-app]

    scripts:
        plugin: dump
        source: snap/scripts
        organize:
          hp-printer-app-server: bin/
        after: [hp-printer-app]
