name: hp-printer-app
base: core18
version: '1.0'
summary: HP Printer Application
description: |
  HP Printer Application is sample printer application for Hewlett Packard PCL
  (and compatible) printers.  It is based on PAPPL (Printer Application
  Framework), a simple C-based framework/library for developing CUPS Printer
  Applications, which are the recommended replacement for printer drivers.

grade: stable
confinement: strict

apps:
  hp-printer-app:
    command: bin/hp-printer-app
    plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

parts:
  pappl:
    plugin: autotools
    configflags: [--enable-libjpeg,--enable-libpng,--enable-libusb,--with-dnssd=avahi]
    source: https://github.com/michaelrsweet/pappl
    source-type: git
    build-packages: [libavahi-client-dev, libcups2-dev, libcupsimage2-dev, libgnutls28-dev, libjpeg-dev, libpam-dev, libpng-dev, libusb-1.0-0-dev, zlib1g-dev]
    stage-packages: [libavahi-client3, libcups2, libcupsimage2, libjpeg, libpng16-16, libusb-1.0-0]

  hp-printer-app:
    plugin: make
    source: .
    after: [pappl]
